calcExp<-function(distrs, genomeDB, pc){
  dexo<-as.data.frame(genomeDB$exonsNI)
  mexo<-as.matrix(dexo[,c(5,4)])
  stafun = ecdf(distrs$stDis)
  #fill<-cbind(0:(min(as.numeric(names(distrs$lenDis)))-1), rep(0, min(as.numeric(names(distrs$lenDis)))))
  #colnames(fill)<-colnames(as.data.frame(lendis))
  #lendis<-as.data.frame(rbind(fill, as.data.frame(distrs$lenDis)))
  #lendis[,2]<-lendis[,2]/sum(lendis[,2])
  fill<-c(rep(0,(min(as.numeric(names(distrs$lenDis))))), distrs$lenDis)
  names(fill)[1:min(as.numeric(names(distrs$lenDis)))]<-0:(min(as.numeric(names(distrs$lenDis)))-1)
  lendis<-as.table(fill/sum(fill))
  exp<-.Call("calc", mexo, genomeDB$newTx, pc, stafun, lendis)
  names(exp)<-names(genomeDB$newTx)
  exp<-as.matrix(exp)
  featureData<-as.numeric(unlist(genomeDB$txs@elementMetadata$gene_id))
  names(featureData)<-as.numeric(unlist(genomeDB$txs@elementMetadata$tx_id))
  featureData<-cbind(featureData, as.numeric(names(featureData)), genomeDB$txs@elementMetadata$tx_name)
  featureData<-as.data.frame(featureData[rownames(exp),])
  colnames(featureData)<-c("gene_id", "tx_id", "tx_name")
  metadata <- data.frame(labelDescription = colnames(featureData), row.names=colnames(featureData))
  featureData<-new("AnnotatedDataFrame", data=featureData, varMetadata=metadata)
  exp<-new("ExpressionSet", exprs=exp, featureData=featureData, annotation="entrez")
  exp
}
