setGeneric("genePlot", function(generanges, islandid, genomeDB, reads, exp, names.arg, xlab='', ylab='', xlim, cex=1, yaxt='n', col, ...) standardGeneric("genePlot"))
setGeneric("getIsland", function(entrezid, txid, genomeDB) standardGeneric("getIsland"))
setGeneric("getChr", function(entrezid, txid, islandid, genomeDB) standardGeneric("getChr"))
setGeneric("getNreads", function(pc) standardGeneric("getNreads"))
setGeneric("getReads", function(x) standardGeneric("getReads"))
setGeneric("plotExpr", function(gene, minProbExpr=.5, minExpr=.1, xlab='(kb)', ylab='', xlim, cex=1, yaxt='n', col, ...) standardGeneric("plotExpr"))
setGeneric("procBam", function(bam, stranded, seed, verbose) standardGeneric("procBam"))
setGeneric("procGenome", function(genDB, genome, txid="tx_id", txname="tx_name", geneid="gene_id", mc.cores=1) standardGeneric("procGenome"))
setGeneric("rangesPlot",function(x, gene, exonProfile=TRUE, maxFragLength=500, xlab='', ylab='', xlim, ...) standardGeneric("rangesPlot"))
setGeneric("transcripts", function(entrezid, islandid, genomeDB) standardGeneric("transcripts"))
